### ISSUE TITLE
Interface 'Silex\ServiceProviderInterface' not found

### ISSUE THREAD

**Issue by kakaeriel** [authbucket/oauth2-php#25]
Im using silex 2.\* and authbucket. After register authbucket in web/index.php:
$app->register(new AuthBucket\OAuth2\Provider\AuthBucketOAuth2ServiceProvider());

im getting error : 

Fatal error: Interface 'Silex\ServiceProviderInterface' not found in ..\vendor\authbucket\oauth2-php\src\Provider\AuthBucketOAuth2ServiceProvider.php on line 34

**Comment by Antoine-Pous** [comment]
Hi, if you want you can test my fix here, i make a PR when all features are tested.

**Comment by hswong3i** [comment]
Already update dependency to "silex/silex" : "~2.0", so issue mark as closed.

See authbucket/oauth2-php@bfa97216e11322b2e9a400f90eda46ed78a887f1 for more information.

P.S. from my point of view, Silex provider is just a bonus for using this library immediately, but not the primary dependency (i.e. require-dev, not require); since I am going to integrate it with Drupal 8.x, even symfony/security is NOT A MUST, too ;-)
